### PR TITLE
Fix/date format

### LINKED ISSUE #1903: Datepicker causes error when saving without touching the given field
The datepicker `parse` function doesn't seem to fire unless the user touches it, causing an invalid date to be sent through. 

`unexpected error - invalid date`. 

The backend may be expecting a format which has been setup by the schema. It may be the case that if you provided a specific format that things will work untouched. Need to do some discovery on if this is an easy fix. 

If this can't be fixed in the next day or so we should just remove the `date` field from the Tina Cloud Starter

### PR DESCRIPTION
**Pull request by jbevis**
Closes #1903 

Discussion surrounding Date and this work covered in this PR, which has become a bit stale.
https://github.com/tinacms/tinacms/pull/1936

Opening a new one for more streamlined review.

Updates the backend to expect and store dates as UTC timestamps. This moves onus to format dates to the developer and outside the concerns of Tina within the sidebar.

### CODE REVIEW

**Review by dwalkr — APPROVED** [review]

File: packages/@tinacms/graphql/src/primitives/resolver/index.ts [hunk 1]
```diff
@@ -530,8 +529,9 @@ export class Resolver {
       case 'string':
         if (field.options) {
           if (field.list) {
+            // FIXME: this is awaiting checkbox suppport
             return {
-              component: 'checkbox-group',
+              component: 'checkbox',
```
Comment (Enigmatical) [inline packages/@tinacms/graphql/src/primitives/resolver/index.ts:534]: I'm not quite sure this PR is up-to-date with the latest changes to `tinacms`?  I believe my PR to convert this to `checkbox-group` was merged in last week?

File: packages/@tinacms/graphql/src/primitives/resolver/index.ts [hunk 2]
```diff
@@ -201,7 +201,6 @@ export class Resolver {
             await this.database.put(realPath, {
               _template: lastItem(template.namespace),
             })
-            return this.getDocument(realPath)
```
Comment (Enigmatical) [inline packages/@tinacms/graphql/src/primitives/resolver/index.ts:204]: And this was to fix the bug with `useDocumentCreator()` and `templates` instead of a `fields`.

**Review by Enigmatical — CHANGES_REQUESTED** [review]
Seems to be based on an out-of-date `tinacms`?  Check comments.

File: packages/@tinacms/graphql/src/primitives/resolver/index.ts (hunk 1 above)
Comment (jbevis) [reply packages/@tinacms/graphql/src/primitives/resolver/index.ts]: Good eye @Enigmatical.

There must have been some oddities locally that made their way into that file, because I do not recall touching those parts of the file. 

Either way, those changes have been reverted.

**Review by Enigmatical — APPROVED** [review]
