### PR TITLE
List Field Meta Wrapper, Form Improvements

### LINKED ISSUE #3495: Object with list: true does not display the error message when its invalid.
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

See video: https://www.loom.com/share/5f592b30174241fd94503d1d4caa801d

Here is a [link to the playground](https://tina-gql-playground.vercel.app/object-list-data?markdownCode=---%0Atestimonials%3A%0A++-+author%3A+Livvy+Abby%0A++++role%3A+CEO%0A++++quote%3A+Lorem+ipsum+dolor+sit+amet+consectetur+adipisicing+elit.+Nemo+expedita+voluptas+culpa+sapiente+alias+molestiae.+Numquam+corrupti+in+laborum+sed+rerum+et+corporis.%0A---&schemaCode=import+%7B+defineSchema%2C+defineConfig+%7D+from+%27tinacms%27%0A%0Aconst+schema+%3D+defineSchema%28%7B%0A++collections%3A+%5B%7B%0A++++label%3A+%22Post%22%2C%0A++++name%3A+%22post%22%2C%0A++++path%3A+%22posts%22%2C%0A++++fields%3A+%5B%7B%0A++++++label%3A+%22Testimonials%22%2C%0A++++++name%3A+%22testimonials%22%2C%0A++++++type%3A+%22object%22%2C%0A++++++list%3A+true%2C%0A++++++ui%3A+%7B%0A++++++++%2F%2F+This+allows+the+customization+of+the+list+item+UI%0A++++++++%2F%2F+Data+can+be+accessed+by+item%3F.%3CName+of+field%3E%0A++++++++itemProps%3A+%28item%29+%3D%3E+%7B%0A++++++++++return+%7B+label%3A+%60%24%7Bitem%3F.author%7D++%28+%24%7Bitem%3F.role%7D+%29+%60%7D%0A++++++++%7D%2C%0A++++++++%2F%2F+Setting+a+default+will+auto-populate+new+items+with+the+given+values%0A++++++++defaultItem%3A+%7B%0A++++++++++author%3A+%22Judith+Black%22%2C%0A++++++++++role%3A+%22CEO%22%2C%0A++++++++++quote%3A+%22Lorem+ipsum+dolor+sit+amet+consectetur+adipisicing+elit.+Nemo+expedita+voluptas+culpa+sapiente+alias+molestiae.+Numquam+corrupti+in+laborum+sed+rerum+et+corporis.%22%0A++++++++%7D%2C%0A++++++++validate%3A+%28val%29+%3D%3E+%7B%0A++++++++++if+%28val+%26%26+val%3F.length+%3E%3D+4%29+%7B%0A++++++++++++return+%27can+not+have+more+then+3+items%27%0A++++++++++%7D%0A++++++++++return+%27%27%0A++++++++%7D%0A++++++%7D%2C%0A++++++fields%3A+%5B%0A++++++++%7B%0A++++++++++label%3A+%22Author%22%2C%0A++++++++++name%3A+%22author%22%2C%0A++++++++++type%3A+%22string%22%0A++++++++%7D%2C%0A++++++++%7B%0A++++++++++label%3A+%22Role%22%2C%0A++++++++++name%3A+%22role%22%2C%0A++++++++++type%3A+%22string%22%0A++++++++%7D%2C%0A++++++++%7B%0A++++++++++label%3A+%22Quote%22%2C%0A++++++++++name%3A+%22quote%22%2C%0A++++++++++type%3A+%22string%22%2C%0A++++++++++ui%3A+%7B%0A++++++++++++component%3A+%22textarea%22%0A++++++++++%7D%0A++++++++%7D%0A++++++%5D%0A++++%7D%5D%0A++%7D%5D%0A%7D%29%0Aexport+default+defineConfig%28%7B+schema+%7D%29%3B%0A&reactCode=import+*+as+React+from+%27react%27%0Aimport+%7B+useTina+%7D+from+%27tinacms%2Fdist%2Freact%27%0A%0A%2F%2F+Note%3A+In+most+cases%2C+this+query+would+be%0A%2F%2F+autogenerated+with+%60client.queries.%3CCollection%3E%60%0A%2F%2F+https%3A%2F%2Ftina.io%2Fdocs%2Ffeatures%2Fdata-fetching%2F%0Aconst+QUERY+%3D+%60query+%7B%0A++post%28relativePath%3A+%22hello-world.md%22%29+%7B%0A++++testimonials+%7B%0A++++++author%0A++++++role%0A++++++quote%0A++++%7D%0A++%7D%0A%7D%60%0A%0Aexport+default+function+Page%28props%29+%7B%0A++const+%7Bdata%2C+isLoading%7D+%3D+useTina%28%7B+query%3A+QUERY%2C%0A++++variables%3A+%7B%7D%2C%0A++++data%3A+props.data%0A++%7D%29%0A%0A++if%28isLoading%29+%7B%0A++++return+%3Cdiv%3ELoading...%3C%2Fdiv%3E%0A++%7D%0A%0A++return+%28%0A++%3Cdiv+className%3D%22relative%22%3E%0A++%7Bdata.post.testimonials%3F.map%28testimonial+%3D%3E+%28%3Cblockquote+className%3D%22mt-10%22%3E%0A++++%3Cdiv+className%3D%22max-w-3xl+mx-auto+text-center+text-xl+leading-9+font-medium+text-gray-900%22%3E%0A++++++%3Cp%3E%0A++++++++%26ldquo%3B%7Btestimonial%3F.quote%7D%26rdquo%3B%0A++++++%3C%2Fp%3E%0A++++%3C%2Fdiv%3E%0A++++%3Cfooter+className%3D%22mt-8%22%3E%0A++++++%3Cdiv+className%3D%22md%3Aflex+md%3Aitems-center+md%3Ajustify-center%22%3E%0A++++++++%3Cdiv+className%3D%22md%3Aflex-shrink-0%22%3E%0A++++++++++%3Cimg%0A++++++++++++className%3D%22mx-auto+h-10+w-10+rounded-full%22%0A++++++++++++src%3D%22https%3A%2F%2Fimages.unsplash.com%2Fphoto-1494790108377-be9c29b29330%3Fixlib%3Drb-1.2.1%26ixid%3DeyJhcHBfaWQiOjEyMDd9%26auto%3Dformat%26fit%3Dfacearea%26facepad%3D2%26w%3D256%26h%3D256%26q%3D80%22%0A++++++++++++alt%3D%22%22%0A++++++++++%2F%3E%0A++++++++%3C%2Fdiv%3E%0A++++++++%3Cdiv+className%3D%22mt-3+text-center+md%3Amt-0+md%3Aml-4+md%3Aflex+md%3Aitems-center%22%3E%0A++++++++++%3Cdiv+className%3D%22text-base+font-medium+text-gray-900%22%3E%7Btestimonial%3F.author%7D%3C%2Fdiv%3E%0A%0A++++++++++%3Csvg+className%3D%22hidden+md%3Ablock+mx-1+h-5+w-5+text-indigo-600%22+fill%3D%22currentColor%22+viewBox%3D%220+0+20+20%22%3E%0A++++++++++++%3Cpath+d%3D%22M11+0h3L9+20H6l5-20z%22+%2F%3E%0A++++++++++%3C%2Fsvg%3E%0A%0A++++++++++%3Cdiv+className%3D%22text-base+font-medium+text-gray-500%22%3E%7Btestimonial%3F.role%7D%3C%2Fdiv%3E%0A++++++++%3C%2Fdiv%3E%0A++++++%3C%2Fdiv%3E%0A++++%3C%2Ffooter%3E%0A++%3C%2Fblockquote%3E%29%29%7D%0A%3C%2Fdiv%3E%0A%29%0A%7D).
 where you can see the issue.

### Reproduction

[link to the playground](https://tina-gql-playground.vercel.app/object-list-data?markdownCode=---%0Atestimonials%3A%0A++-+author%3A+Livvy+Abby%0A++++role%3A+CEO%0A++++quote%3A+Lorem+ipsum+dolor+sit+amet+consectetur+adipisicing+elit.+Nemo+expedita+voluptas+culpa+sapiente+alias+molestiae.+Numquam+corrupti+in+laborum+sed+rerum+et+corporis.%0A---&schemaCode=import+%7B+defineSchema%2C+defineConfig+%7D+from+%27tinacms%27%0A%0Aconst+schema+%3D+defineSchema%28%7B%0A++collections%3A+%5B%7B%0A++++label%3A+%22Post%22%2C%0A++++name%3A+%22post%22%2C%0A++++path%3A+%22posts%22%2C%0A++++fields%3A+%5B%7B%0A++++++label%3A+%22Testimonials%22%2C%0A++++++name%3A+%22testimonials%22%2C%0A++++++type%3A+%22object%22%2C%0A++++++list%3A+true%2C%0A++++++ui%3A+%7B%0A++++++++%2F%2F+This+allows+the+customization+of+the+list+item+UI%0A++++++++%2F%2F+Data+can+be+accessed+by+item%3F.%3CName+of+field%3E%0A++++++++itemProps%3A+%28item%29+%3D%3E+%7B%0A++++++++++return+%7B+label%3A+%60%24%7Bitem%3F.author%7D++%28+%24%7Bitem%3F.role%7D+%29+%60%7D%0A++++++++%7D%2C%0A++++++++%2F%2F+Setting+a+default+will+auto-populate+new+items+with+the+given+values%0A++++++++defaultItem%3A+%7B%0A++++++++++author%3A+%22Judith+Black%22%2C%0A++++++++++role%3A+%22CEO%22%2C%0A++++++++++quote%3A+%22Lorem+ipsum+dolor+sit+amet+consectetur+adipisicing+elit.+Nemo+expedita+voluptas+culpa+sapiente+alias+molestiae.+Numquam+corrupti+in+laborum+sed+rerum+et+corporis.%22%0A++++++++%7D%2C%0A++++++++validate%3A+%28val%29+%3D%3E+%7B%0A++++++++++if+%28val+%26%26+val%3F.length+%3E%3D+4%29+%7B%0A++++++++++++return+%27can+not+have+more+then+3+items%27%0A++++++++++%7D%0A++++++++++return+%27%27%0A++++++++%7D%0A++++++%7D%2C%0A++++++fields%3A+%5B%0A++++++++%7B%0A++++++++++label%3A+%22Author%22%2C%0A++++++++++name%3A+%22author%22%2C%0A++++++++++type%3A+%22string%22%0A++++++++%7D%2C%0A++++++++%7B%0A++++++++++label%3A+%22Role%22%2C%0A++++++++++name%3A+%22role%22%2C%0A++++++++++type%3A+%22string%22%0A++++++++%7D%2C%0A++++++++%7B%0A++++++++++label%3A+%22Quote%22%2C%0A++++++++++name%3A+%22quote%22%2C%0A++++++++++type%3A+%22string%22%2C%0A++++++++++ui%3A+%7B%0A++++++++++++component%3A+%22textarea%22%0A++++++++++%7D%0A++++++++%7D%0A++++++%5D%0A++++%7D%5D%0A++%7D%5D%0A%7D%29%0Aexport+default+defineConfig%28%7B+schema+%7D%29%3B%0A&reactCode=import+*+as+React+from+%27react%27%0Aimport+%7B+useTina+%7D+from+%27tinacms%2Fdist%2Freact%27%0A%0A%2F%2F+Note%3A+In+most+cases%2C+this+query+would+be%0A%2F%2F+autogenerated+with+%60client.queries.%3CCollection%3E%60%0A%2F%2F+https%3A%2F%2Ftina.io%2Fdocs%2Ffeatures%2Fdata-fetching%2F%0Aconst+QUERY+%3D+%60query+%7B%0A++post%28relativePath%3A+%22hello-world.md%22%29+%7B%0A++++testimonials+%7B%0A++++++author%0A++++++role%0A++++++quote%0A++++%7D%0A++%7D%0A%7D%60%0A%0Aexport+default+function+Page%28props%29+%7B%0A++const+%7Bdata%2C+isLoading%7D+%3D+useTina%28%7B+query%3A+QUERY%2C%0A++++variables%3A+%7B%7D%2C%0A++++data%3A+props.data%0A++%7D%29%0A%0A++if%28isLoading%29+%7B%0A++++return+%3Cdiv%3ELoading...%3C%2Fdiv%3E%0A++%7D%0A%0A++return+%28%0A++%3Cdiv+className%3D%22relative%22%3E%0A++%7Bdata.post.testimonials%3F.map%28testimonial+%3D%3E+%28%3Cblockquote+className%3D%22mt-10%22%3E%0A++++%3Cdiv+className%3D%22max-w-3xl+mx-auto+text-center+text-xl+leading-9+font-medium+text-gray-900%22%3E%0A++++++%3Cp%3E%0A++++++++%26ldquo%3B%7Btestimonial%3F.quote%7D%26rdquo%3B%0A++++++%3C%2Fp%3E%0A++++%3C%2Fdiv%3E%0A++++%3Cfooter+className%3D%22mt-8%22%3E%0A++++++%3Cdiv+className%3D%22md%3Aflex+md%3Aitems-center+md%3Ajustify-center%22%3E%0A++++++++%3Cdiv+className%3D%22md%3Aflex-shrink-0%22%3E%0A++++++++++%3Cimg%0A++++++++++++className%3D%22mx-auto+h-10+w-10+rounded-full%22%0A++++++++++++src%3D%22https%3A%2F%2Fimages.unsplash.com%2Fphoto-1494790108377-be9c29b29330%3Fixlib%3Drb-1.2.1%26ixid%3DeyJhcHBfaWQiOjEyMDd9%26auto%3Dformat%26fit%3Dfacearea%26facepad%3D2%26w%3D256%26h%3D256%26q%3D80%22%0A++++++++++++alt%3D%22%22%0A++++++++++%2F%3E%0A++++++++%3C%2Fdiv%3E%0A++++++++%3Cdiv+className%3D%22mt-3+text-center+md%3Amt-0+md%3Aml-4+md%3Aflex+md%3Aitems-center%22%3E%0A++++++++++%3Cdiv+className%3D%22text-base+font-medium+text-gray-900%22%3E%7Btestimonial%3F.author%7D%3C%2Fdiv%3E%0A%0A++++++++++%3Csvg+className%3D%22hidden+md%3Ablock+mx-1+h-5+w-5+text-indigo-600%22+fill%3D%22currentColor%22+viewBox%3D%220+0+20+20%22%3E%0A++++++++++++%3Cpath+d%3D%22M11+0h3L9+20H6l5-20z%22+%2F%3E%0A++++++++++%3C%2Fsvg%3E%0A%0A++++++++++%3Cdiv+className%3D%22text-base+font-medium+text-gray-500%22%3E%7Btestimonial%3F.role%7D%3C%2Fdiv%3E%0A++++++++%3C%2Fdiv%3E%0A++++++%3C%2Fdiv%3E%0A++++%3C%2Ffooter%3E%0A++%3C%2Fblockquote%3E%29%29%7D%0A%3C%2Fdiv%3E%0A%29%0A%7D).
### Steps to reproduce

_No response_

### System Info

```shell
Monorepo
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

### PR DESCRIPTION
**Pull request by spbyrne**
### Video Demo -- Shows both list errors and min/max:
https://user-images.githubusercontent.com/5075484/211587949-a19681e1-f8c9-4f91-820a-f7f55eeb0e6d.mp4

## Fixes Errors

The List, Group List and Block fields weren't displaying errors. I've created a list meta wrapper component that provides the label, description, and error UI. It accepts an 'actions' prop that allows each field to control that logic.

This also updates the error styles to give it a bit more whitespace and a quick slide-in animation.

Fixes #3495

## Adds Min/Max Support

The field UI object now accepts a min and max when the field is `list: true`. If the list/group list/block field is at the max or min value, the add or remove buttons are disabled. If the min and max values are the same, the field is considered 'fixed length' and the add/remove buttons are removed entirely, unless the data is invalid (you can still add items if there's not enough to satisfy the validation).

Screenshot 2023-01-06 at 2 20 47 PM

Here's a field with min and max set to the same number: (no add/remove buttons)
Screenshot 2023-01-10 at 10 39 19 AM

### Fix Form Whitespace

Adds padding at the bottom of forms and removes unnecessary margin from the MDX component (this is provided by the field wrapper). 

Screenshot 2023-01-10 at 10 59 17 AM

### CODE REVIEW

**Comment by logan-anderson** [comment]
@spbyrne It looks like the delete button from the object list is gone. 

here is the example of "Related posts" in the basic-iframe starter.


The field: 
```ts
 {
            type: 'object',
            label: 'Related Posts',
            name: 'posts',
            list: true,
            ui: {
              itemProps: (item) => {
                return { label: item?.label }
              },
            },
            fields: [
              {
                name: 'post',
                type: 'reference',
                collections: ['post', 'page'],
              },
              {
                name: 'label',
                type: 'string',
              },
            ],
          },
```

On main: 
Screen Shot 2023-01-09 at 4 05 12 PM

In the PR:
Screen Shot 2023-01-09 at 4 04 07 PM

**Review by logan-anderson — DISMISSED** [review]
See https://github.com/tinacms/tinacms/pull/3499#issuecomment-1376316884

File: packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx [hunk 1]
```diff
@@ -83,29 +84,40 @@ const Group = ({ tinaForm, form, field, input }: GroupProps) => {
     [field.itemProps]
   )
 
+  // @ts-ignore
+  const isMax = items.length >= (field.max || Infinity)
```
Comment (jamespohalloran) [inline packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:88]: I think this is what we'd want, maybe?
```suggestion
  const isMax = items.length > (field.max || Infinity)
```

File: packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx [hunk 2]
```diff
@@ -83,29 +84,40 @@ const Group = ({ tinaForm, form, field, input }: GroupProps) => {
...
+  // @ts-ignore
+  const isMin = items.length <= (field.min || 0)
```
Comment (jamespohalloran) [inline packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:90]:
```suggestion
  const isMin = items.length < (field.min || 0)
```

File: packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx [hunk 3]
```diff
@@ -83,29 +84,40 @@ const Group = ({ tinaForm, form, field, input }: GroupProps) => {
...
+  // @ts-ignore
+  const fixedLength = field.min === field.max
```
Comment (jamespohalloran) [inline packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:92]: Do we need this check?

File: packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx [hunk 4]
```diff
@@ -188,7 +211,9 @@ const Item = ({ tinaForm, field, index, item, label, ...p }: ItemProps) => {
               <GroupLabel>{title}</GroupLabel>
               <BiPencil className="h-5 w-auto fill-current text-gray-200 group-hover:text-inherit transition-colors duration-150 ease-out" />
             </ItemClickTarget>
-            <ItemDeleteButton onClick={removeItem} />
+            {(!fixedLength || (fixedLength && !isMin)) && (
```
Comment (jamespohalloran) [inline packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:214]: I kind of feel this might be a bit confusing to remove the button rather than just showing an error when we're below the minimum. (Otherwise, the user wouldn't have an error at this point, so there wouldn't be an indication of why they couldn't delete a list-item).

Alternatively, Maybe we could disable the button with a tooltip? (Same goes for the add-button)

File: packages/@tinacms/toolkit/src/packages/fields/plugins/ListFieldPlugin.tsx [hunk 5]
```diff
@@ -90,27 +89,35 @@ const List = ({ tinaForm, form, field, input }: ListProps) => {
     [field.itemProps]
   )
 
+  // @ts-ignore
+  const isMax = items.length >= (field.max || Infinity)
```
Comment (jamespohalloran) [inline packages/@tinacms/toolkit/src/packages/fields/plugins/ListFieldPlugin.tsx:93]: See comments above about our other min/max checks

File: packages/@tinacms/toolkit/src/packages/fields/plugins/ListFieldPlugin.tsx [hunk 6]
```diff
@@ -90,27 +89,35 @@ const List = ({ tinaForm, form, field, input }: ListProps) => {
...
+  // @ts-ignore
+  const isMin = items.length <= (field.min || 0)
+  // @ts-ignore
+  const fixedLength = field.min === field.max
```
Comment (jamespohalloran) [inline packages/@tinacms/toolkit/src/packages/fields/plugins/ListFieldPlugin.tsx:97]: See comments above about our other min/max checks

File: packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx (hunk 4 above)
Comment (spbyrne) [reply packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:214]: This only removes the delete button if the field has min and max set to the same amount and the field meets those requirements, since you'd never be able to delete an item. In other cases it's only ever disabled to indicate you can't currently delete an item but you'd otherwise be able to if you were above the minimum amount.

File: packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx (hunk 1 above)
Comment (spbyrne) [reply packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:88]: If it were `>` a list with 3 items would be considered valid given a max of 2, so we need `>=`.

File: packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx (hunk 2 above)
Comment (spbyrne) [reply packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:90]: Same as what I said above for is max but in reverse. With `<` a list with 0 items would be valid when the min is set to 1.

File: packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx (hunk 3 above)
Comment (spbyrne) [reply packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:92]: It's used to determine if add/remove buttons should be rendered. If they're not the same the UI should only use a disabled state to indicate it can't currently be added/removed.

File: packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx (hunk 1 above)
Comment (spbyrne) [reply packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:88]: `isMax` is used to determine if the add button should be disabled. It should be disabled when the list is as many items long as the max or more.

Comment (spbyrne) [reply packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:88]: Here's a field with `min: 1, max: 3,` set. It has 3 items, so the add button is disabled but the delete buttons aren't.

Screenshot 2023-01-11 at 1 38 14 PM

File: packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx (hunk 3 above)
Comment (spbyrne) [reply packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:92]: Here's a field with `min: 3, max: 3` where the add/remove UI isn't needed at all:

Screenshot 2023-01-11 at 1 39 08 PM

File: packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx (hunk 2 above)
Comment (spbyrne) [reply packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:90]: Here's that same field but with only one item, so the delete button is now disabled but you can add items again:
Screenshot 2023-01-11 at 1 39 59 PM

File: packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx (hunk 1 above)
Comment (jamespohalloran) [reply packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx:88]: ahh, I was thinking that bool was used to show the error message. If it's only used for the button-active-state these comments wouldn't apply

**Review by jamespohalloran — APPROVED** [review]
