### PR TITLE
Fix auth modal close

### LINKED ISSUE #1053: GitHub Authorization modal won't close
#752  Description
Can't close out of the "GitHub Authorization" modal

Screen Shot 2020-04-24 at 3 44 22 PM

### Steps to reproduce

Tried clicking "cancel" and the X in the modal on both the Auth step, and the fork step
Tested on tinacms.org

### Expected result

Modal should close

### Actual result

Modal doesn't close

#### Tinacms Package Versions
```
"next-tinacms-github": "0.1.0-canary4.1",
"react-tinacms-github": "0.1.0-canary3.2",
```

### PR DESCRIPTION
**Pull request by mittonface**
Fixes #1053 

itcloses

### CODE REVIEW

File: packages/react-tinacms-github/src/github-editing-context/TinacmsGithubProvider.tsx [hunk 1]
```diff
@@ -46,6 +46,10 @@ export const TinacmsGithubProvider = ({
   const github: GithubClient = cms.api.github
   const [activeModal, setActiveModal] = useState<ModalNames>(null)
 
+  const onClose = async () => {
```
Comment (kendallstrautman) [inline packages/react-tinacms-github/src/github-editing-context/TinacmsGithubProvider.tsx:49]:
```suggestion
  const onClose = () => {
```

Comment (kendallstrautman) [reply packages/react-tinacms-github/src/github-editing-context/TinacmsGithubProvider.tsx:49]: Not sure this needs to be async?

**Comment by riderx** [comment]
@ncphillips i got the same issue of closing modal with tina cloud !
