### PR TITLE
1993 - Better Error Messaging when linking to Tina Cloud 

### LINKED ISSUE #1993: Better error message when no `.tina` schema files are found
When using Tina Cloud it's possible that the user selects the wrong repo, if that happens they'd get `Unable to find record for .tina/__generated__/_graphql.json`

We should show a more clear error message:

```
We could not find a valid Tina schema at:
Repo: https://github.com/blahblah
Path: src/.tina/graphql/blahblah
Branch: main
```

### PR DESCRIPTION
**Pull request by Enigmatical**
Something Jeff discovered:  In the event a user chooses a GitHub repository lacking a `.tina` and `.tina/__generated__` folder, they are given a very confusing error message.

I've modified the `GraphQLError` messages thrown by the `GithubBridge` to more accurately reference the file, the repository, and the reference (branch) being used.

Additionally, I've added in a suggestion to "confirm" the repository and the existence of `.tina` and `.tina/schema.ts` in the event that the error is throw while looking for the `SYSTEM_FILES`.

Closes #1993

### CODE REVIEW

File: packages/@tinacms/graphql/src/primitives/database/index.ts [hunk 1]
```diff
@@ -45,10 +45,22 @@ export class Database {
...
-      )
-      return JSON.parse(dataString)
+      try {
+        const dataString = await this.bridge.get(
+          path.join(GENERATED_FOLDER, `${filepath}.json`)
+        )
+        return JSON.parse(dataString)
+      } catch (err) {
+        /** File Not Found */
+        if (err instanceof GraphQLError && err.extensions?.status === 404) {
```
Comment (jeffsee55) [inline packages/@tinacms/graphql/src/primitives/database/index.ts:55]: 👍

**Review by jeffsee55 — APPROVED** [review]
