### PR TITLE
Fix/admin work in docker container

### LINKED ISSUE #3480: Admin page not working in Docker container
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Dockerizing an app prevents the admin page from loading, it shows a blank page with errors in the browser console:
```
admin:17 GET http://localhost:5173/@vite/client net::ERR_CONNECTION_REFUSED
admin:21 GET http://localhost:5173/admin/src/main.tsx net::ERR_CONNECTION_REFUSED
admin:11 GET http://localhost:5173/@react-refresh net::ERR_CONNECTION_REFUSED
```

Proposed solution: "We would have to add  {host: true,} in our vite config."
See Discord thread: https://discordapp.com/channels/835168149439643678/835172431836479508/1053054057784279141

### Reproduction

https://github.com/tinacms/tina-cloud-starter

### Steps to reproduce

Run from Docker container, here's a sample dockerfile:
```
FROM node:alpine
WORKDIR /app
COPY . /app
EXPOSE 3000
CMD [ "yarn", "dev" ]
```

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 556.67 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/vidyard/website/node_modules/.bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 103.0.1
    Safari: 16.1
  npmPackages:
    @tinacms/cli: ^1.0.0 => 1.0.3
    tinacms: ^1.1.0 => 1.1.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

### PR DESCRIPTION
**Pull request by logan-anderson**
Fixes #3480

### CODE REVIEW

File: packages/@tinacms/app/src/index.ts [hunk 1]
```diff
@@ -150,6 +150,7 @@ export const viteBuild = async ({
       target: 'es2020',
     },
     server: {
+      host: true,
```
Comment (jeffsee55) [inline packages/@tinacms/app/src/index.ts:153]: Is this a good default to have? Would it be better allow either an env variable or CLI flag to set this? And otherwise leave it off?

Comment (logan-anderson) [reply packages/@tinacms/app/src/index.ts:153]: That makes sense.

**Review by kldavis4 — APPROVED** [review]

**Review by jamespohalloran — APPROVED** [review]
