### PR TITLE
fix: not possible to come out of code mark which is at end of line

### LINKED ISSUE #922: Can't move right of inline code at the end of the line
## Description

It's possible to get stuck inside code-ticks at the end of the line.

### Steps to reproduce

Go to the end of a document and write the following:
```markdown
`test`
```
It will get turned into inline code.

Press the left-arrow and then the right-arrow twice

Type any character and it will be inside the inline code.

### Expected result

Pressing right a second time should push you out of the inline code. An analogous behavior exists in Slack

### PR DESCRIPTION
**Pull request by jpuri**
If user is in code mark at end of line a arrow right will bring him out of it.

Fix #922

### CODE REVIEW

File: packages/react-tinacms-editor/src/state/plugins/Common/index.tsx [hunk 1]
```diff
@@ -62,5 +63,26 @@ export const commonPlugin = new Plugin({
...
+      const selectionIsAtEnd =
+        selection.$to.node().nodeSize - 2 === selection.$to.parentOffset
+      if (!selectionIsAtEnd) return false
+      const { state, dispatch } = view
+      dispatch(
+        state.tr
+          .insertText(' ', selection.$to.pos)
+          .removeMark(selection.$to.pos, selection.$to.pos + 1, code)
+      )
+      return true
```
Comment (ncphillips) [inline packages/react-tinacms-editor/src/state/plugins/Common/index.tsx:85]: Awesome! Could you just extract this to it's own function? Maybe something like `exitCodeMarkOnArrowRight`

```ts
handleKeyDown(view, event) {
  return exitCodeMarkOnArrowRight(view, event)
}
```

**Comment by DirtyF** [comment]
When you delete a line starting with `inline code` and type again on the same line
Then text is still formatted as `inline code`
When you hit return and backspace
Then text is no more formated as inline code

https://www.loom.com/share/0b47424528e844b2ae6aee06e3f7634a

**Comment by jpuri** [comment]
Hey @ncphillips : PR is updated.
