### PR TITLE
2548 - Adds loading indicators throughout TinaAdmin

### LINKED ISSUE #2548: Loading Indicator for main panel in TinaAdmin
## Description

Currently there is no loading indicator in the main panel of TinaAdmin, which makes it pretty hard to understand for content editors that the system is loading something / is doing something, when changing from one collection to another while the other collection having a significant amount of documents.

Loom:
https://www.loom.com/share/e9bc1fb6fed3429eb1fcc3dbd110a765

### Steps to reproduce

1. Have 2 collections in TinaCloud
2. Have one collection with ~ 30 documents
3. Change from one collection to the other with ~ 30 documents
4. See that there is no visual indication that something is loading in the background, but still TinaCloud takes a significant amount of time to load the documents from Github API.

### Expected result

Display a loading indicator while updating the main panel

### Actual result

The previos state is displayed.

#### Tinacms Package Versions

```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.4
├── next-tinacms-cloudinary@3.5.5
├── tinacms@0.66.1

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |

### PR DESCRIPTION
**Pull request by Enigmatical**
While locally, the Admin is snappy, in production or on Tina Cloud, there is some delay in loading a Collection List or Document.

Before, there was no way to tell that the request had even been made - resulting in potentially repeat clicking (which would further increase the delay) or a general lack of confidence that the Admin was even working.  This PR adds a simple acitivity indicator through the Admin for _most_ of the requests.

Closes #2548

### CODE REVIEW

File: packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx [hunk 1]
```diff
@@ -75,32 +75,23 @@ interface SidebarProps {
...
-    loading: true,
-    error: false,
-    collections: [],
-  })
+  const [collections, setCollections] = useState<any[]>([])
+  const [loading, setLoading] = useState<boolean>(true)
 
   useEffect(() => {
     const fetchCollections = async () => {
       const response = await cms.api.admin.fetchCollections()
```
Comment (logan-anderson) [inline packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx:83]: Should we do a try / catch to handle an error for if this fetch fails?

Comment (Enigmatical) [reply packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx:83]: In a desire to get this out quickly, I put error handling outside the scope.  This is only for happy path loading.  I've got another card for adding in try / catch and error handling:
https://github.com/tinacms/tinacms/issues/2600

Comment (Enigmatical) [reply packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx:83]: This does set the foundation for that.  I've got a POC branch locally that does it; just don't want to hold up this Quality of Life improvement for that.

Comment (logan-anderson) [reply packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx:83]: Makes sense to me!

**Review by logan-anderson — APPROVED** [review]
🎉  This is awesome
