### PR TITLE
UI Bug Fixes

### LINKED ISSUE #906: Sidebar: Markdown toolbar z-index above color picker
## Description

The Markdown Toolbar z-index is set super high, which is good unless you have another 'popup' type field that is active and _should_ sit above it. See image. 

Screen Shot 2020-03-13 at 11 56 29 AM

### Steps to reproduce

Add a color field next to a markdown field in the sidebar. Open the color picker. Observable on the info page of [brevifolia-next-tinacms](https://github.com/kendallstrautman/brevifolia-next-tinacms)

### Expected result

The color picker, or whatever 'popup' field that is active should be on top. 

### Actual result

The markdown toolbar remains on top no matter what.

#### Tinacms Package Versions

```text
├─┬ @tinacms/api-git@0.7.0
├── @tinacms/git-client@0.6.0
├── next-tinacms-json@0.3.5
├─┬ next-tinacms-markdown@0.2.5
├─┬ tinacms@0.16.0
│ ├── @tinacms/core@0.7.2
│ ├─┬ @tinacms/fields@0.7.0
│ ├─┬ @tinacms/form-builder@0.2.16
│ ├─┬ @tinacms/forms@0.2.1
│ ├── @tinacms/icons@0.7.0
│ ├─┬ @tinacms/react-core@0.2.8
│ ├── @tinacms/styles@0.3.0
```

### PR DESCRIPTION
**Pull request by spbyrne**
* Fix color picker popup z-index, 
* Uses Tina theme colors for date picker popup

closes #906

### CODE REVIEW

File: packages/@tinacms/fields/src/components/ColorPicker/ColorPicker.tsx [hunk 1]
```diff
@@ -103,7 +103,7 @@ export const Popover = styled.div`
   transform: translate3d(-50%, 5px, 0) scale3d(1, 1, 1);
   transform-origin: 50% -8px;
   animation: ${ColorPopupKeyframes} 85ms ease-out both 1;
-  z-index: 900;
+  z-index: 99999 !important;
```
Comment (ncphillips) [inline packages/@tinacms/fields/src/components/ColorPicker/ColorPicker.tsx:106]: 😂 you sure buddy?

Comment (spbyrne) [reply packages/@tinacms/fields/src/components/ColorPicker/ColorPicker.tsx:106]: I just copied what the date picker was using since it worked. But we could have some CSS custom properties set up for z-index.
