### PR TITLE
fix: update beforeSubmit logic to fix issue with saved changes indicator not working

### LINKED ISSUE #4332: Save changes indicator not updating
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Saved changes indicator not working as expected. See reproduction repo and loom video.

### Reproduction

https://github.com/kldavis4/sorumeiji-website-starter-template

### Steps to reproduce

See video https://www.loom.com/share/0648380417804600bd0c3fc56a12ba84?sid=fa0b8c43-bec0-4f32-bb40-48a6dc5f5b35

### System Info

```shell
na
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

### PR DESCRIPTION
**Pull request by kldavis4**
Fix #4332

### CODE REVIEW

File: packages/tinacms/src/toolkit/form-builder/form-builder.tsx [hunk 1]
```diff
@@ -111,6 +111,17 @@ export const FormBuilder: FC<FormBuilderProps> = ({
...
+
+  React.useEffect(() => {
+    const collection = schema.getCollectionByFullPath(tinaForm.relativePath)
+    if (collection?.ui?.beforeSubmit) {
+      tinaForm.beforeSubmit = (values: any) =>
+        collection.ui.beforeSubmit({ cms, form: tinaForm, values })
+    } else {
+      tinaForm.beforeSubmit = undefined
+    }
+  }, [tinaForm.relativePath])
```
Comment (kldavis4) [inline packages/tinacms/src/toolkit/form-builder/form-builder.tsx:124]: wasn't sure if the form is updated so put this in a useEffect to be safe. let me know if it should be pulled out

**Review by logan-anderson — APPROVED** [review]
